name: Flickr
fileGroups: [
  Flickr,
  FlickrTests,
  FlickrUITests
]

configs:
  Prod-Debug: debug
  Prod-Release: release 
  Dev-Debug: debug
  Dev-Release: release

schemes:
  Flickr:
    build:
      targets:
        Flickr: all
        FlickrTests: [analyze, test, profile]
        FlickrUITests: [analyze, test, profile]
    run:
      config: Prod-Debug
    archive:
      config: Prod-Release
    test:
      config: Prod-Debug
      targets: [FlickrTests, FlickrUITests]

  Flickr-Dev:
    build:
      targets:
        Flickr: all
        FlickrTests: [analyze, test, profile]
        FlickrUITests: [analyze, test, profile]
    run:
      config: Dev-Debug
    archive:
      config: Dev-Release
    test:
      config: Dev-Debug
      targets: [FlickrTests, FlickrUITests]

targets:
  Flickr:
    configFiles:
      Dev-Debug: Flickr/Configs/Dev/Dev-Debug.xcconfig
      Dev-Release: Flickr/Configs/Dev/Dev-Release.xcconfig
      Prod-Debug: Flickr/Configs/Prod/Prod-Debug.xcconfig
      Prod-Release: Flickr/Configs/Prod/Prod-Release.xcconfig
    type: application
    platform: iOS
    deploymentTarget: 11.0
    sources:
      - path: Flickr/Strings
        buildPhase: resources
      - path: Flickr/Sources
        buildPhase: sources
      - path: Flickr/Resources
        buildPhase: resources
      - path: Flickr/Theme
        buildPhase: sources
        
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.suryadigital.flickr"
        DEVELOPMENT_TEAM: "000000"
        INFOPLIST_FILE: Flickr/Plist/Info.plist
        TARGETED_DEVICE_FAMILY: 1
        
    preBuildScripts:
      - name: swiftlint
        script: >
            if $SRCROOT/bin/swiftlint --version >/dev/null; then
              $SRCROOT/bin/swiftlint --config "$SRCROOT/.swiftlint.yml"
            else
              echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
            fi
      - script: "\"$PODS_ROOT/R.swift/rswift\" generate \"$SRCROOT/Flickr/Theme/R/R.generated.swift\""
        name: "R.swift"
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/Flickr/Theme/R/R.generated.swift

  FlickrTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 11.0
    sources:
      - path: FlickrTests/Sources
        buildPhase: sources
    dependencies:
      - target: Flickr
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.suryadigital.flickr.tests"
        INFOPLIST_FILE: FlickrTests/Plist/Info.plist

  FlickrUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: 11.0
    sources:
      - path: FlickrUITests/Sources
        buildPhase: sources
    dependencies:
      - target: Flickr
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.suryadigital.flickr.ui-tests"
        DEVELOPMENT_TEAM: "000000"
        INFOPLIST_FILE: FlickrUITests/Plist/Info.plist
        TARGETED_DEVICE_FAMILY: 1
