name: PR-Check

on: pull_request

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set GitHub Token to URLs
      shell: bash
      run: |
        sed -E 's|git@github.com:(..*).git|https://${{ secrets.PRVT_REPO_ACCESS }}@github.com/\1|g' Podfile > Podfile.backup
        mv Podfile.backup Podfile
    - name: Generate project
      run: ./create-xcworkspace.sh

    - name: Xcode build and test iPhone 8 iOS 15.0
      uses: ./.github/actions/run-tests
      with:
        destination: "'platform=iOS Simulator,OS=15.2,name=iPhone 8'"
        workspace: Flickr.xcworkspace
        scheme: Flickr
        xcode_build_output_file: xcodebuild.json
          # Update the Dangerfile if additional iOS build tests are added.

    - name: Run Danger
      if: ${{always()}}
      run: bundle exec danger
      env:
        GITHUB_USERNAME: ${{github.actor}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
